
setup.ilm.enabled: false
xpack.monitoring.enabled: false

lsbeat:
  period: 30s 
  paths: ${BLUECATS_WATCH_FOLDERS:nothing}
  depth: ${BLUECATS_WATCH_FOLDER_DEPTH:1}

output.logstash:
  enabled: true
  hosts: ${BLUECATS_HOST:?환경변수 값으로 BLUECATS_HOST값을 127.0.0.1:7700 과 같은 형태로 추가하세요.}

processors:
- add_locale: ~
- add_host_metadata:
    netinfo.enabled: true  
- add_tags:
    tags: ${BLUECATS_SITE}
- add_fields:
    target: beat
    fields:
      version: VERSION_INFO_HERE    
- add_fields:
    target: mirero
    fields:
      kafka_topic: lsbeat
      dms50: ${BLUECATS_DMS50:false}
      mss10: ${BLUECATS_MSS10:false}
      
- add_tags:
    tags: [dms, dms50]
    when: 
      equals:
        mirero.dms50: true         
- add_tags:
    tags: [midews, mss, mss10]
    when: 
      equals:
        mirero.mss10: true
